services:
  pdfutils-ui:
    container_name: pdfutils-ui
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    # environment:
    #   PORT: ${PORT}
    #   BASE_URL: ${BASE_URL}
    network_mode: bridge
    develop:
      watch:
        - action: sync
          path: ./static
          target: /usr/share/nginx/html/